In [1]:
import pandas as pd
from pathlib import Path
import sys
import os

In [3]:
sys.path.append(os.path.abspath(".."))

# Importando a função
from src.data_loader import carregar_dados, carregar_bases_adicionais

In [4]:
df = carregar_dados()

2026-09-29 22:16:47.402 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-09-29 22:16:47.403 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-29 22:16:47,404 - INFO - Baixando base consolidada de acidentes do Google Drive...

In [5]:
df_add = carregar_bases_adicionais()

2026-09-29 22:20:45.013 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-09-29 22:20:45.026 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-29 22:20:45,038 - INFO - Baixando 'frota_media_consolidada_2023_2025' do Google Drive (ID: 1H8CHfMJbwDLCxzi6zwR7ulUmleaOZKij)...
Downloading...
From: https://drive.google.com/uc?id=1H8CHfMJbwDLCxzi6zwR7ulUmleaOZKij
To: C:\Users\felip\PythonProjects\prf-analytics\data\raw\frota_media_consolidada_2023_2025.csv
100%|██████████| 47.6M/47.6M [00:06<00:00, 7.28MB/s]
2026-09-29 22:20:55,736 - INFO - Base 'frota_media_consolidada_2023_2025' carregada com sucesso.
2026-09-29 22:20:55,737 - INFO - Baixando 'frota_agrupada_por_estado_2023_2025' do Google Drive (ID: 1vkXWiFWymu52T9Uytu1PSj3nx-SRY8Jj)...
Downloading...
From: https://drive.google.com/uc?id=1vkXWiFWymu52T9Uytu1PSj3nx-SRY8Jj
To: C:\Users\felip\PythonProjects\prf-analytics\data\raw\frota_agrupada_por_estado_2023_2025.csv
100%|██████████| 897k/897k [00:00<00:00, 2.42MB/s]
2026-09-29 22:20:58,950 - INFO - Base 'frota_agrupada_por_estado_2023_2025' carregada com sucesso.

In [6]:
caminho = r'..\data\raw\frota_agrupada_por_estado_2023_2025.csv'
df = pd.read_csv(caminho)
df.head()

     uf   ano tipo_veiculo especie_veiculo  eixos  qtd_veiculos
0  ACRE  2023    AUTOMOVEL           CARGA      0          11.5
1  ACRE  2023    AUTOMOVEL           CARGA      2           1.0
2  ACRE  2023    AUTOMOVEL         COLECAO      0          14.0
3  ACRE  2023    AUTOMOVEL        ESPECIAL      0           2.0
4  ACRE  2023    AUTOMOVEL        ESPECIAL      2           2.0

In [8]:
caminho2 = r'..\data\raw\frota_media_consolidada_2023_2025.csv'
df2 = pd.read_csv(caminho2)
df2.head()

     uf   ano   municipio tipo_veiculo especie_veiculo  eixos  qtd_veiculos
0  ACRE  2023  ACRELANDIA    AUTOMOVEL         COLECAO      0      1.000000
1  ACRE  2023  ACRELANDIA    AUTOMOVEL      PASSAGEIRO      0   1230.500000
2  ACRE  2023  ACRELANDIA    AUTOMOVEL      PASSAGEIRO      2    522.250000
3  ACRE  2023  ACRELANDIA     CAMINHAO           CARGA      0    156.166667
4  ACRE  2023  ACRELANDIA     CAMINHAO           CARGA      1      3.000000